### PR TITLE
Add admin module

### PR DESCRIPTION
**Pull request by unixzii**
This PR adds admin module to provide several admin commands (like `/set_public`, `/add_member`, etc.) and user access control.

### CODE REVIEW

**Comment by ktiays** [comment]
Should we also update the document?

**Comment by unixzii** [comment]
That's a good point, we need to add some explanations of how to use the admin features.

**Comment by unixzii** [comment]
> Should we also update the document?

@ktiays  It's done, I think we can merge it now.

**Review by ktiays — APPROVED** [review]
LGTM, merging it right now.

**Pull request merged**
